shared:
  image: node:8
  steps:
    - echo: echo hi
jobs:
  component:
      requires: [~commit, ~pr, ~sd@44:y6]
  remove_in_progress_dist_tag:
      requires: []
  promote_test_it_to_tested:
      requires: []
  promote_and_remove:
      requires: [~sd@48:rypt]
