shared:
  image: node:8
  steps:
    - echo: echo hi
jobs:
  pull-request:
    requires: []

  component:
    requires: [~commit, ~pr, ~sd@45:component]

  sfs:
    requires:
      - ~component

  sfsp:
    requires: [~sd@47:ft]
