shared:
  image: node:8
  steps:
    - echo: echo hi
jobs:
  component:
    requires:
      - ~commit
      - ~pr
  rypt:
    requires: [~sd@46:sfsp]
  rypt2:
    requires: [~sd@111:sfrysp]
  rrpt:
    requires: [~sd@222:sfrrsp]
  rapt:
    requires: [~sd@333:sfrasp]
