shared:
  image: node:8
  steps:
    - echo: echo hi
jobs:
  functional-test:
    requires: [~sd@46:sfs]
  failover-test:
    requires:
      - ~functional-test
  functional-ryt:
    requires: [~sd@111:sfrys]
  failover-ryt:
    requires:
      - ~functional-ryt
  functional-rrt:
    requires: [~sd@111:sfrrs]
  failover-rrt:
    requires:
      - ~functional-rrt
  functional-rat:
    requires: [~sd@222:sfras]
  failover-rat:
    requires:
      - ~functional-rat
  component:
    requires:
      - ~commit
      - ~pr
